#url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Random Hacks Of Kindness Banglaore
email: rishibhatnagar1@gmail.com
description: "RHOK Bangalore is the Bangalore chapter of Random Hacks of Kindness Global"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Chinmayi S K
  pic: 1
  position: Volunteer
  social:
    - title: twitter
      url: @skchinmayi
    #- title: facebook
    #  url: #
    #- title: stack-overflow
    #  url: #

- name: Rishi Gaurav Bhatnagar
  pic: 2
  position: Volunteer
  social:
    - title: twitter
      url: @rishigb
    #- title: facebook
    #  url: #
    #- title: linkedin
    #  url: #

- name: Yogesh L
  pic: 3
  position: Volunteer
  social:
    - title: twitter
      url: @yogi_Londhe 
    #- title: facebook
    #  url: #
    #- title: google-plus
    #  url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/rhoh_bang
  - title: facebook
    url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket 
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/rhokbangalore/

# Postal address (add as many lines as necessary)
address:
  - line: Bangalore
  - line: India

# Build settings
markdown: kramdown
permalink: pretty